version: '2.1'

networks:
  webgateway:
    driver: 'bridge'

services:
  api:
    image: api
    restart: always
    build: .
    depends_on:
      - mongodb
    ports:
      - 443:3000
      - 80:3000
    networks:
      - webgateway

  mongodb:
    image: mongo
    restart: always
    networks:
      - webgateway

